name: Trigger News.yml Workflow

on:
  workflow_run:
    workflows:
      - "news.yml"
    types:
      - completed
  workflow_dispatch:
  
jobs:
  trigger_news_yml:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger "news.yml" workflow manually
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/news.yml/dispatches" \
            -d '{"ref": "main"}'
