name: Trigger News.yml Workflow

on:
  workflow_run:
    workflows:
      - "news.yml"
    types:
      - completed
  workflow_dispatch:

jobs:
  trigger_news_yml:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger "news.yml" workflow
        uses: actions/workflow-dispatch@v2
        with:
          workflow: news.yml
          token: ${{ secrets.GITHUB_TOKEN }}
