name: Check and Trigger News Workflow

on:
  schedule:
    - cron: '0 */1 * * *'  # Run every hour, adjust as needed

jobs:
  check_and_trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Check if News Workflow is running
        id: check_news_status
        run: |
          RUNNING_WORKFLOW=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                              "https://api.github.com/repos/${{ github.repository }}/actions/runs?event=workflow_dispatch" \
                              | jq '.workflow_runs | .[] | select(.name == "News Workflow" and .status == "in_progress")')

          if [ -z "$RUNNING_WORKFLOW" ]; then
            echo "News Workflow is not running. Triggering a new run."
            echo "::set-output name=trigger_run::true"
          else
            echo "News Workflow is already running. Skipping trigger."
            echo "::set-output name=trigger_run::false"
          fi

      - name: Trigger News Workflow
        if: steps.check_news_status.outputs.trigger_run == 'true'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/news.yml/dispatches" \
            -d '{"ref":"main"}'
