name: Stop and Run news.yml

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  stop-workflows:
    name: Stop workflows
    runs-on: ubuntu-latest
    steps:
      - name: Cancel running workflows
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: ID_OF_NEWS.yml_WORKFLOW
  trigger-new-run:
    name: Trigger new run
    needs: stop-workflows
    runs-on: ubuntu-latest
    steps:
      - name: Trigger new run of news.yml
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: news.yml
          token: ${{ secrets.GITHUB_TOKEN }}
