name: Close and Trigger New News Workflow

on:
  workflow_dispatch

jobs:
  close-and-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Close running workflows
        id: close_workflows
        run: |
          runs=$(gh workflow run list --workflow news.yml -R ${{ github.repository }} --json id --query '[].id' --state running)
          echo "Running workflow runs: $runs"

          if [ "$runs" != "null" ]; then
            for run_id in $(echo $runs | jq -r '.[]'); do
              gh workflow run cancel $run_id -R ${{ github.repository }}
              echo "Closed workflow run: $run_id"
            done
          else
            echo "No running workflows to close."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger new news workflow
        if: steps.close_workflows.outputs.runs != 'null'
        run: gh workflow run news.yml -R ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
