name: Run App Forever

on:
  workflow_dispatch: # Manual trigger

jobs:
  run-app:
    runs-on: ubuntu-latest

    env:
      NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      LASTMILEAI_API_KEY: ${{ secrets.LASTMILEAI_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
            sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
            echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | \
            sudo tee /etc/apt/sources.list.d/ngrok.list && \
            sudo apt update && sudo apt install ngrok

      - name: Authenticate ngrok
        run: ngrok config add-authtoken $NGROK_TOKEN

      - name: Start ngrok
        run: ngrok http --domain=handy-labrador-humane.ngrok-free.app 5000 &

      - name: Run App
        run: nohup python app.py &

      - name: Check App Status
        run: |
          # Add a command to check if your app is running, e.g., by making an HTTP request.
          # Replace the placeholder URL with the appropriate endpoint or port.
          until curl -s -o /dev/null http://localhost:5000; do
            sleep 5
          done
