name: Run App Forever

on:
  workflow_dispatch: # Manual trigger

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ngrok
        run: |
          sudo tar xvzf ~/Downloads/ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin

      - name: Start ngrok
        run: ngrok http --domain=handy-labrador-humane.ngrok-free.app 5000 &

      - name: Run App Forever
        run: |
          nohup python app.py &  # Run app in the background
          echo $! > app_pid.txt  # Save the process ID to a file for later reference
