name: Run App Forever

on:
  workflow_dispatch: # Manual trigger

jobs:
  run-app:
    runs-on: ubuntu-latest

    env:
      NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      LASTMILEAI_API_KEY: ${{ secrets.LASTMILEAI_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
            sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
            echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | \
            sudo tee /etc/apt/sources.list.d/ngrok.list && \
            sudo apt update && sudo apt install ngrok
          
      - name: Authenticate ngrok
        run: ngrok config add-authtoken $NGROK_TOKEN

      - name: Start ngrok
        run: ngrok http --domain=handy-labrador-humane.ngrok-free.app 5000 &

      - name: Run App Forever
        run: |
          nohup python app.py &  # Run app in the background
          echo $! > app_pid.txt  # Save the process ID to a file for later reference
          sleep 21000  # Sleep for 5 hours and 50 minutes

  trigger-new-job:
    needs: run-app
    runs-on: ubuntu-latest
    if: always()  # Ensure this job runs even if the previous job fails

    steps:
      - name: Trigger New Job
        run: echo "Triggering a new job"
